config/routes.rb
EmailApp::Application.routes.draw do
  resources :contacts
  root :to => "contacts#new"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, :presence => true, :format => { :with => /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new; end
  def create
    contact = Contact.create(params[:contact])
    if contact.save
      flash[:notice] = "contact saved"
    else
      error_string = contact.errors.map do |field, error|
        field.to_s.gsub('_',' ') + ' ' + error + '.'
      end.join('<br/>')
      flash[:error] = "#{error_string}".html_safe
        
    end
    redirect_to new_contact_path
  end
  def index
    @contacts = Contact.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/index.html.haml
%ul
  - @contacts.each do |contact|
    %li
      = contact.name
      = contact.email
      =link_to "edit", '#'
      =link_to "delete", '#'

app/views/contacts/new.html.haml
%h2 Add a Contact
=form_for Contact.new do |f|
  .fields
    .field
      =f.label :name
      =f.text_field :name
    .field
      =f.label :email
      =f.text_field :email
  =f.submit "+"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cottage Game Night Mailing List</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <% if flash[:notice] %>
      <div class="notice">
        <%= flash[:notice] %>
      </div>
      <% elsif flash[:error] %>
        <div class="error">
          <%= flash[:error] %>
        </div>
      <% end %>
    <div class="main">
      <%= yield %>
    </div>

    <ul class="nav">
      <li><%=link_to "Add Contact", root_path%></li>
      <li><%=link_to "See All", contacts_path%></li>
    </ul>
  </body>
</html>